### ISSUE TITLE
Problème to 

### ISSUE THREAD

**Issue by alexwilliamlex** [Wikifab/wikifab-main#15]
Hello J'ai un souci quand je veux l'installer. 
Quand je fais "sudo php maintenance/update.php"  où "php maintenance/update.php"
ça me met cette  erreur 
`
root@alexwilliam:/home/awdev/public_html/wiki# PHP Fatal error:  Cannot use $this as parameter in /home/awdev/public_html/wiki/extensions/WfextStyle/wikifabstyle.php on line 20
-bash: PHP: command not found
`

**Comment by pierreboutet** [comment]
Bonjour, 
ce problème est du à PHP 7, il a été corrigé dans la release 1.2.0-beta
