### ISSUE TITLE
[Solved] Error in install script PHP Fatal error:  Cannot use $this

### ISSUE THREAD

**Issue by julienrat** [Wikifab/wikifab-main#17]
When i ran this following command `php maintenance/update.php`
I had this error : `PHP Fatal error:  Cannot use $this as parameter in /srv/http/wikifab/wikifab/extensions/WfextStyle/wikifabstyle.php on line 20`

I have just remove `$this` in line 20 to solve the problem

**Comment by pierreboutet** [comment]
Hello,
this bug has already been corrected. it is solved in the latest release 1.2.0-beta
