### ISSUE TITLE
Class 'EchoEvent' not found

### ISSUE THREAD

**Issue by OndroNR** [Wikifab/wikifab-main#2]
I get error during final installation step. I followed first method.

```
$ php maintenance/initWikifab.php --setWikifabHomePage
Setting Up wikifab pages ...
Setting wiki home page 1
page Main Page successfully created.
PHP Fatal error:  Class 'EchoEvent' not found in /data/www/xxxx/extensions/UsersWatchButton/includes/CombinedWatchlist/NotificationHook.php on line 70
```

I tried to add it to composer.local.json and run composer update. Did not help.

**Comment by pierreboutet** [comment]
Hi,

Sorry for that, we are currently adding new notification Feature, and it seem to make fail this install.

For now, you can edit the file LocalSettings.wikifab.php, and remove the line  : 
require_once "$IP/extensions/UsersWatchButton/UsersWatchButton.php";

it should make it work.

We should manage to add the Echo extension soon, I will back to you. 
(you will be able to update after if you already have install your wiki)

**Comment by OndroNR** [comment]
Hi, thanks, that worked for now.
