### ISSUE TITLE
 No driver found to handle VCS repository

### ISSUE THREAD

**Issue by medchedli** [Wikifab/wikifab-main#3]
Hi,
When running **php composer.phar update command** I get suddenly: No driver found to handle VCS repository.

```
`Loading composer repositories with package information

  [InvalidArgumentException]                                                                           
  No driver found to handle VCS repository https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Flow  

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...`

```

![capture du 2016-09-07 17 26 10](https://cloud.githubusercontent.com/assets/3912825/18320048/32a1d0ba-7520-11e6-8596-b8059bc95dc9.png)

well, thank you. any hint is welcome.

**Comment by pierreboutet** [comment]
Hello,

I think it was required to install some things to access gerrit repositories, I changed the file composer.local.json to use git mirror repository for this extension ( git@github.com:wikimedia/mediawiki-extensions-Flow.git ) 
if you update this file and try again it should work.

**Comment by abdonor** [comment]
This can have a lot of different possibilities, but it also happen when your repository is linked with ssh private/public keys, and your private key is unprotected. The solution is to set it to 600, example below:

    sudo chmod 600 ~/.ssh/id_rsa
