### ISSUE TITLE
Undefined index: de in initWikifabClass.php on line 58

### ISSUE THREAD

**Issue by ShopNix** [Wikifab/wikifab-main#33]
PHP Notice:  Undefined index: de in /var/www/vario/htdocs/wiki/maintenance/initWikifabClass.php on line 58

**Comment by darkworks** [comment]
make sure you using php 7.2 ~ 7.3 , if you on php 7.4 then u will encounter problems

**Comment by ShopNix** [comment]
I am using PHP 7.0.33-0ubuntu0.16.04.15

**Comment by darkworks** [comment]
hmmm update your php to 7.2 then try ,

**Comment by ShopNix** [comment]
Sorry, but I can't update because of some other software. 

By the way: I can't believe in a versions problem in case of of an missing index. It seems related to i18n, and index 'de' stands for the german language.

**Comment by darkworks** [comment]
i had played with this script its unstable , have issues during installation on php 7.0 and php 7.4 ,  
check  : https://www.mediawiki.org/wiki/Compatibility

**Comment by ShopNix** [comment]
Thank you.
