### ISSUE TITLE
Link to newest version

### ISSUE THREAD

**Issue by bryanwares** [Wikifab/wikifab-main#38]
Can you please provide link to latest version of wikifab.
Last version shows as beta that was uploaded 4 years back.

Thank you for your support.

**Comment by timmwille** [comment]
Would be amazing to see this revive → I can find support if needed?

**Comment by bryanwares** [comment]
I am willing to sponsor for this revival with $$$.Please someone come forward
    On Friday, July 7, 2023 at 04:34:23 AM CDT, Timm ***@***.***> wrote:  
 
 


Would be amazing to see this revive → I can find support if needed?

**Comment by timmwille** [comment]
I have followed up on this in the past months via other communication channels @bryanwares  We just had a meeting with members of wikifab, lowtechlab and osegermany and hopefully by around March 2024 things will change. 


For now I think the best help would be to help specify the current bugs/updates that need fixing and highlight the importance of certain features or the community edition of itself. 

I'll be doing my part as I think too this needs a revival :)

**Comment by bryanwares** [comment]
Thank you @timmwille 
Let me know if the group need financial support to update to a new version.

**Comment by bryanwares** [comment]
@timmwille @pierreboutet 
March 24 has come and gone but no progress here.

" hopefully by around March 2024 things will change"

**Comment by bryanwares** [comment]
@timmwille @pierreboutet @ClementFlipo 
I will willing to sponsor this project to get upgraded to latest version. Please let me know how much money is required in USD.

**Comment by timmwille** [comment]
Thank you @bryanwares for being consistent in reminding. I will try through my other channels to reach the team and see how this might be maintained through https://dokit.io/ or if this does not work out we can Talk about Plan B:

- Facilitate an Upgrade of Mediawiki via Open Source Ecology Germany association (or our Partner opentoolchain.org) via Pull Request
- Talk about the Maintenance Future of Wikifab as a software but also wikifab.org that will require a bit of Service to keep up to date and handle issues etc. - I think this still needs a bit of guidance from the initial inventors or at least some collaboration with dokit.io to pick up


(I have only a rough idea what is needed to upgrade, e.g. https://gitlab.com/hydrawiki/extensions/Tabber still in place? or other external and self made extensions and adjustments)


So either way I think it is not only a budget and time issue but also the question of who will take the responsibility for the public, open source administration to kick this back to life for the community. It is worth it, that is for sure!

**Comment by bryanwares** [comment]
@timmwille 
Thank you for the reply.
1. First step is to upload the latest version similar to working version at https://demo.dokit.io/wiki/Main_Page
Since they already have a working copy there on dokit, it shouldn't take much of an effort if they really want this to be opensource.
2. Next step is on-going maintenance and support as you mentioned.
As I mentioned, I am willing to fund it either with your plan A or B.
Many thanks!

**Comment by timmwille** [comment]
@bryanwares I think in terms of Open Source this is what to look at: https://demo.dokit.io/wiki/Special:Version

Dokit.io is not all Open Source as far as I know, some modules might be enterprise edition, only the core surrounding Mediawiki is. Which in itself is fine, so all the wikifab.org related community edition is the one to look at but it looks very similar on first check: https://wikifab.org/wiki/Special:Version 

Still quite some updates could be made, though I understand this takes time that needs to be available. I'll check back as soon as I know more. Hoping for the best :)

**Comment by timmwille** [comment]
also interesting to look at by the way:
https://github.com/mat100/wikifab-main

**Comment by bryanwares** [comment]
@timmwille 
Thank you for your efforts.
If someone can help upload https://wikifab.org/wiki/Special:Version
this would be a great start.

**Comment by ClementFlipo** [comment]
Hi Friends,
Thank you so much for your message and support!
The past few months have been incredibly busy, working on some other projects. 
We are still on the verge of merging Dokit with a French company that has great ambitions for Dokit and its Open Source version as well. The acquisition process naturally takes time, and unfortunately, we are currently pressed for time.
Please allow us a few more months (before September, certainly) to finalize this deal. We will then reopen the discussion with you and them to determine the best way to collaborate.
Best,
Clément

**Comment by bryanwares** [comment]
@ClementFlipo 
Thank you for the reply after many years and thank you for the offer to support open source before September.
Can you please let me know what does it take to upload latest version of https://wikifab.org/wiki/Special:Version
to github in a week or two. I will fund it. September is too late in a fast moving world.. we need it now.
You are also not responding to any dokit sales and even the website has been down for months before it came back up.

**Comment by bryanwares** [comment]
@ClementFlipo 
We are willing to pay 100,000.00 euros.
We sent you message sometime back to get a copy of dokit for our use (not for sale but only for our use - one site).
Can you upload this version of  https://demo.dokit.io/wiki/Special:Version modules to github and/or sell us a copy of dokit for 100,000.00 euros.
We are located in the U.S.

**Comment by ClementFlipo** [comment]
Hi @bryanwares
Thanks for your interest and sorry for not being available.
Send me an email at clement@dokit.io so that we can setup a visoconference and understand your needs.
Thanks and Regards, Clément

**Comment by bryanwares** [comment]
@ClementFlipo 
We are contacting you soon along with my colleague.

**Comment by bryanwares** [comment]
@ClementFlipo Can you kindly respond to Mr. Reddy's email sent to you. Thank you!
