### ISSUE TITLE
JS : TypeError: Cannot read property 'indexOf'

### ISSUE THREAD

**Issue by timfalcucci** [Wikifab/wikifab-main#4]
Hello,
we have the following error in the console when we load a page to modify a tuto... And with this bug we can't add a step when we modify a tuto. No problem on the creation page...

TypeError: Cannot read property 'indexOf' of undefined TypeError: Cannot read property 'indexOf' of undefined(…)
load.php?debug=false&lang=fr&modules=jquery%2Cmediawiki&only=scripts&skin=chameleon&version=OSODX7Te:178 

Our server is running with PHP 5.6

Do you have any suggestion for us ?

**Comment by pierreboutet** [comment]
Hello,

I never had this kind of error. To have more information about it, could you add "?debug=true" to the url of the edit page (or "&debug=true" if url already have a part after "?" ) 
then try again end give the error you get in the console (you should have a more precise location)

Have all also try with an other browser ? (Which one do you use ?)

Thanks

**Comment by timfalcucci** [comment]
Solved !
Sorry for this message, we found a solution. 
We upload a clean version of LocalSettings.php, modify it with our server info and it works...
It was just a problem due to a bad LocalSettings files...

Thanks for your reply ! :)
