### ISSUE TITLE
BUG: No (Open Source) License template option shown to pick from anymore

### ISSUE THREAD

**Issue by timmwille** [Wikifab/wikifab-main#40]
![grafik](https://github.com/Wikifab/wikifab-main/assets/8081055/c370ca79-6a82-4c02-9d6b-396f18cb7535)

This makes a lot of projects meant to be open source less accessible and also new projects are missing this option now.

On https://wiki.lowtechlab.org it seems to work

I also confirmed with another Tutorial in another language:
https://wikifab.org/wiki/ZAC%2B_Kathodentester-Zelle

**Comment by ClementFlipo** [comment]
Hi @timmwille 
It's supposed to be fixed! I'll close the issue. Let me know if you face any problem regarding this license issue.
Thanks
