### ISSUE TITLE
BUG: Missing "Material" and "Tools" Section 

### ISSUE THREAD

**Issue by timmwille** [Wikifab/wikifab-main#41]
> Side Note: by the way I would switch them, if one can not find all tools required, no meaning to look for the materials :smile: 

![grafik](https://github.com/Wikifab/wikifab-main/assets/8081055/8712a5a0-a7af-4654-a29a-e04282f2815d)

this is what it looks on the front but when moving into "edit" it can not be updated:

![grafik](https://github.com/Wikifab/wikifab-main/assets/8081055/072b2cd3-215d-48cb-8eff-15fb7db404cb)

https://wikifab.org/wiki/DIY_Water_Filter

**Comment by ClementFlipo** [comment]
It's back @timmwille

**Comment by timmwille** [comment]
wohoo, so in my view this makes the platform together with #40 now usable again for now, I will share further details I noticed, but its a big help having those two fixed together with the now again working annotations for images 

thank you @ClementFlipo !
