### ISSUE TITLE
issue with the creation of the miniature

### ISSUE THREAD

**Issue by BabyOnMove** [Wikifab/wikifab-main#6]
Hi Dear,
I have freshly installed the wikifab on my OVH hosting and I can run it with no much issue. 
except that I have an issue with the creation of the miniature. 

The error message is the following:
_"Erreur lors de la création de la miniature : 
Error code: -1"_

Do you know why this isn't working and which sub module is used for the rendering of the miniature as this is going to help me to troubleshoot

**Comment by pierreboutet** [comment]
Hi,

Miniature  generation requires the php GD library, or ImageMagick see https://www.mediawiki.org/wiki/Manual:Installing_third-party_tools#Image_thumbnailing for more information and links.
I don't know if OVH web hosting has php-gd library enable, or how to enable it. But it should be possible.

Also, check the permission on the directory 'images' and the subdirs, server must have write access.

**Comment by BabyOnMove** [comment]
Hi Pierre, 

Thanks for the information, at then end it is an issue that has got self corrected. 
after the creation of my 3rd tutorial I then go not more issue on the miniature

Cheers, 
Julien
