### ISSUE TITLE
Display tutorials on main page, like it does on wikifab.org

### ISSUE THREAD

**Issue by petervanderwalt** [Wikifab/wikifab-main#9]
OK (: This time I did legitly spend a few minutes digging and trying to figure it out. 

So, I created a few sample tutorials. 

On my Main_Page I see:

```Oops, your search yielded no results... Consider enlarging the criteria to find more results```

until I use the WFfilter to select something, say Creation... The it displays my Tutorials.

On Wikifab.org, you show some tutorials, even before selecting a filter (: - How do I go about doing that?

**Comment by pierreboutet** [comment]
Hello,
have you changed the fields in the tutorial template ? I am not sure of whet is your issue, but here is a lead :
The search engine in semantic mediawiki do not accept empty queries, so in wikifab.org, to select all tutorials, we set a default query  to select all tutorials. The default query is "[[area::!none]]" to select  tutorials with a 'Area' value (all tutorials have it).
But if you changed fields, and do not have 'area', you can change the default query by settings this in LocalSettings.php (here if all tutorials have the field 'type') : 
`$wfexploreDefaultQuery = '[[type::!none]]';`

Can I see your site, or is it private ?

**Comment by petervanderwalt** [comment]
Thanks for the tips! Will dig in deep tonight (I work US hours (UTC -4), although I'm in GMT+2 hehe, therefore my tonight )

Have not changed the tutorial templates at all.  Looking at the source of a test tutorial, I have:

```
{Tuto Details
|Type=Creation
|Area=Electronics, Modular Build System, Software
|Description=dsfdsf
|Difficulty=Very easy
|Cost=1
|Currency=USD ($)
|Duration=10
|Duration-type=day(s)
|Licences=GNU Free Hardware Designs
|Main_Picture=No-image-yet.jpg
}}
```
so,  [[area::!none]] should still work. 

I just did a clean install onto my localhost (xammps on windows) to eval this, but so far, totally happy. 

Only change was to do the steps in https://github.com/Wikifab/wikifab-main/blob/master/docs/configuration_notes.md#updating-the-categories

I will migrate it to our webhost tonight so i can share it with you if theres more questions.

**Comment by petervanderwalt** [comment]
PS: Quick check, just to validate search works: Searched for "area::!none" and it finds the test tut if thats any clues
![image](https://user-images.githubusercontent.com/31449271/39567552-a3c00b52-4ebf-11e8-86ce-fbd9c253ff2c.png)

**Comment by petervanderwalt** [comment]
Okay, did a fresh clean install on http://docs.openbuilds.com/index.php?title=Main_Page for you.  

This is just https://github.com/Wikifab/wikifab-main#method-1--installation-process-using-the-full-package followed to a tee. Right after the last step (php maintenance/initWikifab.php --setWikifabHomePage) I logged in, and created a test tutorial, nothing else done/customised/changed at all.  

And nope, doesnt display on the front page (: 

So, seems like its something out-of-the-box in the latest http://releases.wikifab.org/wikifab/wikifabFullPackage-0.2.1.zip?

**Comment by petervanderwalt** [comment]
PS: Going to continue just by adding the images and updating logo from https://github.com/Wikifab/wikifab-main/blob/master/docs/configuration_notes.md - so if you look later, you might see those added.  Want to get it in place as I have to show my boss this when he gets in in an hour (;

**Comment by pierreboutet** [comment]
I realise the link in the doc is not the one to the latest version, could you try again with the package https://github.com/Wikifab/wikifab-main/releases/download/1.1.0-rc10/wikifab-1.1.0-rc10.zip
?
you should not need to redo all the install process, just upload the latest package, keep your current file LocalSettings.php, and re run the scripts
`php maintenance/update.php
php maintenance/update.php
php maintenance/initWikifab.php --setWikifabHomePage`

**Comment by petervanderwalt** [comment]
Sweeet that fixed it!   We can close this one (: 
(Maybe just mental note to update link in readme (; 

Thanks a million for all your help. Really, i love this project!  This is what Wikis has needed for sooooo long!
